### ISSUE TITLE
Tag Doesn't Exist: Hexagon Banner

### ISSUE THREAD

**Issue by LunarDev-git** [Darkhax-Minecraft/AdditionalBanners#37] opened 2023-04-08 16:03 UTC
# Client Information

MC version: 1.19.2
Mod Version: 1.19.2-10.1.6
Forge Version: 43.2.8

## Bug Information

Cannot craft the hexagon pattern. This is the only mod besides JEI that I have enabled. 

![image](https://user-images.githubusercontent.com/105180230/230731109-0a887178-d5d5-46cd-a94c-c7192fee0a8b.png)

**Comment by Darkhax** [comment] 2023-04-08 19:44
Thanks for letting me know about this. This is definitely an oversight on my part and affects a few MC versions. I will push some updates very soon.

**Comment by Darkhax** [comment] 2023-04-08 20:00
This issue should now be fixed, just update the game and it should work as intended. 

- 1.18.2 fixed in 7.0.8
- 1.19.2 fixed in 10.1.7
- 1.19.3 fixed in 11.0.3
- 1.19.4 fixed in 12.0.3

**Closed as completed by Darkhax** 2023-04-08 20:00 UTC
